# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://blog.androz2091.fr
  - name: DDPE
    url: https://ddpe.androz2091.fr
  - name: Diswho
    url: https://diswho.androz2091.fr
  - name: Umami Analytics
    url: https://analytics.androz2091.fr
  - name: Plex
    url: https://plex.androz2091.fr
  - name: Jellyfin
    url: https://jellyfin.androz2091.fr
  - name: Cloud
    url: https://cloud.androz2091.fr
  - name: DL
    url: https://dl.androz2091.fr
  - name: Peertube
    url: https://peertube.androz2091.fr
  - name: Hastebin
    url: https://hastebin.androz2091.fr
  - name: My GitHub Stats API
    url: https://my-gh-stats.androz2091.fr
  - name: QBittorrent
    url: https://qbt.androz2091.fr
  - name: Instaddict
    url: https://instaddict.androz2091.fr
  - name: Online Love Calc
    url: https://love-calc.androz2091.fr
  - name: Slash Commands GUI
    url: https://slash-commands-gui.androz2091.fr
  - name: Twittycord
    url: https://twittycord.com
  - name: ManageInvite
    url: https://manage-invite.xyz
  - name: Eat now
    url: https://eat-now.smn.tools
 

status-website:
  cname: ismyserverworki.ng
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Simon** - aka Androz2091 - **services status page**"
  introMessage: This page shows the status of the services and projects hosted on my servers.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
